# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e05416ad7d0fd506b95f6aac3f167df07cb74faa62ca10a382cd2f51101ebb94eca8752b7d8c85713976d3ebdc74858fd29c6b214ca36ba41f35170938c4956e

test:
  secret_key_base: ecec3f7372bd68e185edd1a5f498cd12e8d94b1d7f10b812a917376d507e65042bccd2ad0e150de7eedf719afece0c6abf02d35581d7b90934ecfff2d8318d45

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
